const egyptBuildings = {
    "Small Home": {
        "Building_Egypt_Home_Small_1": "/allied-cultures/buildings/Egypt_Small_Home_Lv1.webp",
        "Building_Egypt_Home_Small_2": "/allied-cultures/buildings/Egypt_Small_Home_Lv2.webp",
        "Building_Egypt_Home_Small_3": "/allied-cultures/buildings/Egypt_Small_Home_Lv3.webp",
        "Building_Egypt_Home_Small_4": "/allied-cultures/buildings/Egypt_Small_Home_Lv4.webp",
        "Building_Egypt_Home_Small_5": "/allied-cultures/buildings/Egypt_Small_Home_Lv5.webp",
        "Building_Egypt_Home_Small_6": "/allied-cultures/buildings/Egypt_Small_Home_Lv6.webp",
    },
    "Average Home": {
        "Building_Egypt_Home_Average_1": "/allied-cultures/buildings/Egypt_Average_Home_Lv1.webp",
        "Building_Egypt_Home_Average_2": "/allied-cultures/buildings/Egypt_Average_Home_Lv2.webp",
        "Building_Egypt_Home_Average_3": "/allied-cultures/buildings/Egypt_Average_Home_Lv3.webp",
        "Building_Egypt_Home_Average_4": "/allied-cultures/buildings/Egypt_Average_Home_Lv4.webp",
        "Building_Egypt_Home_Average_5": "/allied-cultures/buildings/Egypt_Average_Home_Lv5.webp",
        "Building_Egypt_Home_Average_6": "/allied-cultures/buildings/Egypt_Average_Home_Lv6.webp",
    },
    "Luxurious Home": {
        "Building_Egypt_Home_Premium_1": "/allied-cultures/buildings/Egypt_Luxurious_Home_Lv1.webp",
        "Building_Egypt_Home_Premium_2": "/allied-cultures/buildings/Egypt_Luxurious_Home_Lv1.webp",
        "Building_Egypt_Home_Premium_3": "/allied-cultures/buildings/Egypt_Luxurious_Home_Lv1.webp",
        "Building_Egypt_Home_Premium_4": "/allied-cultures/buildings/Egypt_Luxurious_Home_Lv4.webp",
        "Building_Egypt_Home_Premium_5": "/allied-cultures/buildings/Egypt_Luxurious_Home_Lv4.webp",
        "Building_Egypt_Home_Premium_6": "/allied-cultures/buildings/Egypt_Luxurious_Home_Lv4.webp",
    },
    "Papyrus Field": {
        "Building_Egypt_PapyrusField_Average_1": "/allied-cultures/buildings/Egypt_Papyrus_Field_Lv1.webp",
        "Building_Egypt_PapyrusField_Average_2": "/allied-cultures/buildings/Egypt_Papyrus_Field_Lv2.webp",
        "Building_Egypt_PapyrusField_Average_3": "/allied-cultures/buildings/Egypt_Papyrus_Field_Lv3.webp",
        "Building_Egypt_PapyrusField_Average_4": "/allied-cultures/buildings/Egypt_Papyrus_Field_Lv4.webp",
        "Building_Egypt_PapyrusField_Average_5": "/allied-cultures/buildings/Egypt_Papyrus_Field_Lv5.webp",
        "Building_Egypt_PapyrusField_Average_6": "/allied-cultures/buildings/Egypt_Papyrus_Field_Lv6.webp",
    },
    "Luxurious Papyrus Field": {
        "Building_Egypt_PapyrusField_Premium_1": "/allied-cultures/buildings/Egypt_Luxurious_Papyrus_Field_Lv1.webp",
        "Building_Egypt_PapyrusField_Premium_2": "/allied-cultures/buildings/Egypt_Luxurious_Papyrus_Field_Lv1.webp",
        "Building_Egypt_PapyrusField_Premium_3": "/allied-cultures/buildings/Egypt_Luxurious_Papyrus_Field_Lv1.webp",
        "Building_Egypt_PapyrusField_Premium_4": "/allied-cultures/buildings/Egypt_Luxurious_Papyrus_Field_Lv4.webp",
        "Building_Egypt_PapyrusField_Premium_5": "/allied-cultures/buildings/Egypt_Luxurious_Papyrus_Field_Lv4.webp",
        "Building_Egypt_PapyrusField_Premium_6": "/allied-cultures/buildings/Egypt_Luxurious_Papyrus_Field_Lv4.webp",
    },
    "Gold Mine": {
        "Building_Egypt_GoldMine_Average_1": "/allied-cultures/buildings/Egypt_Gold_Mine_Lv1.webp",
        "Building_Egypt_GoldMine_Average_2": "/allied-cultures/buildings/Egypt_Gold_Mine_Lv2.webp",
        "Building_Egypt_GoldMine_Average_3": "/allied-cultures/buildings/Egypt_Gold_Mine_Lv3.webp",
        "Building_Egypt_GoldMine_Average_4": "/allied-cultures/buildings/Egypt_Gold_Mine_Lv4.webp",
        "Building_Egypt_GoldMine_Average_5": "/allied-cultures/buildings/Egypt_Gold_Mine_Lv5.webp",
        "Building_Egypt_GoldMine_Average_6": "/allied-cultures/buildings/Egypt_Gold_Mine_Lv6.webp",
    },
    "Luxurious Gold Mine": {
        "Building_Egypt_GoldMine_Premium_1": "/allied-cultures/buildings/Egypt_Luxurious_Gold_Mine_Lv1.webp",
        "Building_Egypt_GoldMine_Premium_2": "/allied-cultures/buildings/Egypt_Luxurious_Gold_Mine_Lv1.webp",
        "Building_Egypt_GoldMine_Premium_3": "/allied-cultures/buildings/Egypt_Luxurious_Gold_Mine_Lv1.webp",
        "Building_Egypt_GoldMine_Premium_4": "/allied-cultures/buildings/Egypt_Luxurious_Gold_Mine_Lv4.webp",
        "Building_Egypt_GoldMine_Premium_5": "/allied-cultures/buildings/Egypt_Luxurious_Gold_Mine_Lv4.webp",
        "Building_Egypt_GoldMine_Premium_6": "/allied-cultures/buildings/Egypt_Luxurious_Gold_Mine_Lv4.webp",
    },
    "Papyrus Press": {
        "Building_Egypt_Workshop_PapyrusPress_1": "/allied-cultures/buildings/Egypt_Papyrus_Press_Lv1.webp",
        "Building_Egypt_Workshop_PapyrusPress_2": "/allied-cultures/buildings/Egypt_Papyrus_Press_Lv1.webp",
        "Building_Egypt_Workshop_PapyrusPress_3": "/allied-cultures/buildings/Egypt_Papyrus_Press_Lv1.webp",
        "Building_Egypt_Workshop_PapyrusPress_4": "/allied-cultures/buildings/Egypt_Papyrus_Press_Lv4.webp",
        "Building_Egypt_Workshop_PapyrusPress_5": "/allied-cultures/buildings/Egypt_Papyrus_Press_Lv4.webp",
        "Building_Egypt_Workshop_PapyrusPress_6": "/allied-cultures/buildings/Egypt_Papyrus_Press_Lv4.webp",
    },
    "Goldsmith": {
        "Building_Egypt_Workshop_Goldsmith_1": "/allied-cultures/buildings/Egypt_Goldsmith_Lv1.webp",
        "Building_Egypt_Workshop_Goldsmith_2": "/allied-cultures/buildings/Egypt_Goldsmith_Lv1.webp",
        "Building_Egypt_Workshop_Goldsmith_3": "/allied-cultures/buildings/Egypt_Goldsmith_Lv1.webp",
        "Building_Egypt_Workshop_Goldsmith_4": "/allied-cultures/buildings/Egypt_Goldsmith_Lv4.webp",
        "Building_Egypt_Workshop_Goldsmith_5": "/allied-cultures/buildings/Egypt_Goldsmith_Lv4.webp",
        "Building_Egypt_Workshop_Goldsmith_6": "/allied-cultures/buildings/Egypt_Goldsmith_Lv4.webp",
    },
    "Small Well": {
        "Building_Egypt_Irrigation_SmallWell_1": "/allied-cultures/buildings/Egypt_Small_Well.webp",
        "Building_Egypt_Irrigation_SmallWell_2": "/allied-cultures/buildings/Egypt_Small_Well.webp",
        "Building_Egypt_Irrigation_SmallWell_3": "/allied-cultures/buildings/Egypt_Small_Well.webp",
        "Building_Egypt_Irrigation_SmallWell_4": "/allied-cultures/buildings/Egypt_Small_Well.webp",
        "Building_Egypt_Irrigation_SmallWell_5": "/allied-cultures/buildings/Egypt_Small_Well.webp",
        "Building_Egypt_Irrigation_SmallWell_6": "/allied-cultures/buildings/Egypt_Small_Well.webp",
    },
    "Channel": {
        "Building_Egypt_Irrigation_Channel_1": "/allied-cultures/buildings/Egypt_Channel.webp",
        "Building_Egypt_Irrigation_Channel_2": "/allied-cultures/buildings/Egypt_Channel.webp",
        "Building_Egypt_Irrigation_Channel_3": "/allied-cultures/buildings/Egypt_Channel.webp",
        "Building_Egypt_Irrigation_Channel_4": "/allied-cultures/buildings/Egypt_Channel.webp",
        "Building_Egypt_Irrigation_Channel_5": "/allied-cultures/buildings/Egypt_Channel.webp",
        "Building_Egypt_Irrigation_Channel_6": "/allied-cultures/buildings/Egypt_Channel.webp",
    },
    "Water Pump": {
        "Building_Egypt_Irrigation_WaterPump_1": "/allied-cultures/buildings/Egypt_Water_Pump.webp",
        "Building_Egypt_Irrigation_WaterPump_2": "/allied-cultures/buildings/Egypt_Water_Pump.webp",
        "Building_Egypt_Irrigation_WaterPump_3": "/allied-cultures/buildings/Egypt_Water_Pump.webp",
        "Building_Egypt_Irrigation_WaterPump_4": "/allied-cultures/buildings/Egypt_Water_Pump.webp",
        "Building_Egypt_Irrigation_WaterPump_5": "/allied-cultures/buildings/Egypt_Water_Pump.webp",
        "Building_Egypt_Irrigation_WaterPump_6": "/allied-cultures/buildings/Egypt_Water_Pump.webp",
    },
    "Irrigation Station": {
        "Building_Egypt_Irrigation_IrrigationStation_1": "/allied-cultures/buildings/Egypt_Irrigation_Station.webp",
        "Building_Egypt_Irrigation_IrrigationStation_2": "/allied-cultures/buildings/Egypt_Irrigation_Station.webp",
        "Building_Egypt_Irrigation_IrrigationStation_3": "/allied-cultures/buildings/Egypt_Irrigation_Station.webp",
        "Building_Egypt_Irrigation_IrrigationStation_4": "/allied-cultures/buildings/Egypt_Irrigation_Station.webp",
        "Building_Egypt_Irrigation_IrrigationStation_5": "/allied-cultures/buildings/Egypt_Irrigation_Station.webp",
        "Building_Egypt_Irrigation_IrrigationStation_6": "/allied-cultures/buildings/Egypt_Irrigation_Station.webp",
    },
    "Oasis": {
        "Building_Egypt_Irrigation_Oasis_1": "/allied-cultures/buildings/Egypt_Oasis.webp",
        "Building_Egypt_Irrigation_Oasis_2": "/allied-cultures/buildings/Egypt_Oasis.webp",
        "Building_Egypt_Irrigation_Oasis_3": "/allied-cultures/buildings/Egypt_Oasis.webp",
        "Building_Egypt_Irrigation_Oasis_4": "/allied-cultures/buildings/Egypt_Oasis.webp",
        "Building_Egypt_Irrigation_Oasis_5": "/allied-cultures/buildings/Egypt_Oasis.webp",
        "Building_Egypt_Irrigation_Oasis_6": "/allied-cultures/buildings/Egypt_Oasis.webp",
    },
    "Fountain": {
        "Building_Egypt_Irrigation_Fountain_1": "/allied-cultures/buildings/Egypt_Fountain.webp",
        "Building_Egypt_Irrigation_Fountain_2": "/allied-cultures/buildings/Egypt_Fountain.webp",
        "Building_Egypt_Irrigation_Fountain_3": "/allied-cultures/buildings/Egypt_Fountain.webp",
        "Building_Egypt_Irrigation_Fountain_4": "/allied-cultures/buildings/Egypt_Fountain.webp",
        "Building_Egypt_Irrigation_Fountain_5": "/allied-cultures/buildings/Egypt_Fountain.webp",
        "Building_Egypt_Irrigation_Fountain_6": "/allied-cultures/buildings/Egypt_Fountain.webp",
    },
}

const chinaBuildings = {
    "Small Home": {
        "Building_China_Home_Small_1": "/allied-cultures/buildings/China_Small_Home_Lv1.webp",
        "Building_China_Home_Small_2": "/allied-cultures/buildings/China_Small_Home_Lv2.webp",
        "Building_China_Home_Small_3": "/allied-cultures/buildings/China_Small_Home_Lv3.webp",
        "Building_China_Home_Small_4": "/allied-cultures/buildings/China_Small_Home_Lv4.webp",
        "Building_China_Home_Small_5": "/allied-cultures/buildings/China_Small_Home_Lv5.webp",
        "Building_China_Home_Small_6": "/allied-cultures/buildings/China_Small_Home_Lv6.webp",
    },
    "Average Home": {
        "Building_China_Home_Average_1": "/allied-cultures/buildings/China_Average_Home_Lv1.webp",
        "Building_China_Home_Average_2": "/allied-cultures/buildings/China_Average_Home_Lv2.webp",
        "Building_China_Home_Average_3": "/allied-cultures/buildings/China_Average_Home_Lv3.webp",
        "Building_China_Home_Average_4": "/allied-cultures/buildings/China_Average_Home_Lv4.webp",
        "Building_China_Home_Average_5": "/allied-cultures/buildings/China_Average_Home_Lv5.webp",
        "Building_China_Home_Average_6": "/allied-cultures/buildings/China_Average_Home_Lv6.webp",
    },
    "Luxurious Home": {
        "Building_China_Home_Premium_1": "/allied-cultures/buildings/China_Luxurious_Home_Lv1.webp",
        "Building_China_Home_Premium_2": "/allied-cultures/buildings/China_Luxurious_Home_Lv1.webp",
        "Building_China_Home_Premium_3": "/allied-cultures/buildings/China_Luxurious_Home_Lv1.webp",
        "Building_China_Home_Premium_4": "/allied-cultures/buildings/China_Luxurious_Home_Lv4.webp",
        "Building_China_Home_Premium_5": "/allied-cultures/buildings/China_Luxurious_Home_Lv4.webp",
        "Building_China_Home_Premium_6": "/allied-cultures/buildings/China_Luxurious_Home_Lv4.webp",
    },
    "Rice Farm": {
        "Building_China_RiceFarm_Average_1": "/allied-cultures/buildings/China_Rice_Farm_Lv1.webp",
        "Building_China_RiceFarm_Average_2": "/allied-cultures/buildings/China_Rice_Farm_Lv2.webp",
        "Building_China_RiceFarm_Average_3": "/allied-cultures/buildings/China_Rice_Farm_Lv3.webp",
        "Building_China_RiceFarm_Average_4": "/allied-cultures/buildings/China_Rice_Farm_Lv4.webp",
        "Building_China_RiceFarm_Average_5": "/allied-cultures/buildings/China_Rice_Farm_Lv5.webp",
        "Building_China_RiceFarm_Average_6": "/allied-cultures/buildings/China_Rice_Farm_Lv6.webp",
    },
    "Luxurious Rice Farm": {
        "Building_China_RiceFarm_Premium_1": "/allied-cultures/buildings/China_Luxurious_Rice_Farm_Lv1.webp",
        "Building_China_RiceFarm_Premium_2": "/allied-cultures/buildings/China_Luxurious_Rice_Farm_Lv1.webp",
        "Building_China_RiceFarm_Premium_3": "/allied-cultures/buildings/China_Luxurious_Rice_Farm_Lv1.webp",
        "Building_China_RiceFarm_Premium_4": "/allied-cultures/buildings/China_Luxurious_Rice_Farm_Lv4.webp",
        "Building_China_RiceFarm_Premium_5": "/allied-cultures/buildings/China_Luxurious_Rice_Farm_Lv4.webp",
        "Building_China_RiceFarm_Premium_6": "/allied-cultures/buildings/China_Luxurious_Rice_Farm_Lv4.webp",
    },
    "Thread Processor": {
        "Building_China_Workshop_ThreadProcessor_1": "/allied-cultures/buildings/China_Thread_Processor.webp",
        "Building_China_Workshop_ThreadProcessor_2": "/allied-cultures/buildings/China_Thread_Processor.webp",
        "Building_China_Workshop_ThreadProcessor_3": "/allied-cultures/buildings/China_Thread_Processor.webp",
        "Building_China_Workshop_ThreadProcessor_4": "/allied-cultures/buildings/China_Thread_Processor.webp",
        "Building_China_Workshop_ThreadProcessor_5": "/allied-cultures/buildings/China_Thread_Processor.webp",
        "Building_China_Workshop_ThreadProcessor_6": "/allied-cultures/buildings/China_Thread_Processor.webp",
    },
    "Silk Workshop": {
        "Building_China_Workshop_SilkWorkshop_1": "/allied-cultures/buildings/China_Silk_Workshop.webp",
        "Building_China_Workshop_SilkWorkshop_2": "/allied-cultures/buildings/China_Silk_Workshop.webp",
        "Building_China_Workshop_SilkWorkshop_3": "/allied-cultures/buildings/China_Silk_Workshop.webp",
        "Building_China_Workshop_SilkWorkshop_4": "/allied-cultures/buildings/China_Silk_Workshop.webp",
        "Building_China_Workshop_SilkWorkshop_5": "/allied-cultures/buildings/China_Silk_Workshop.webp",
        "Building_China_Workshop_SilkWorkshop_6": "/allied-cultures/buildings/China_Silk_Workshop.webp",
    },
    "Clay Processor": {
        "Building_China_Workshop_ClayProcessor_1": "/allied-cultures/buildings/China_Clay_Processor.webp",
        "Building_China_Workshop_ClayProcessor_2": "/allied-cultures/buildings/China_Clay_Processor.webp",
        "Building_China_Workshop_ClayProcessor_3": "/allied-cultures/buildings/China_Clay_Processor.webp",
        "Building_China_Workshop_ClayProcessor_4": "/allied-cultures/buildings/China_Clay_Processor.webp",
        "Building_China_Workshop_ClayProcessor_5": "/allied-cultures/buildings/China_Clay_Processor.webp",
        "Building_China_Workshop_ClayProcessor_6": "/allied-cultures/buildings/China_Clay_Processor.webp",
    },
    "Porcelain Workshop": {
        "Building_China_Workshop_PorcelainWorkshop_1": "/allied-cultures/buildings/China_Porcelain_Workshop.webp",
        "Building_China_Workshop_PorcelainWorkshop_2": "/allied-cultures/buildings/China_Porcelain_Workshop.webp",
        "Building_China_Workshop_PorcelainWorkshop_3": "/allied-cultures/buildings/China_Porcelain_Workshop.webp",
        "Building_China_Workshop_PorcelainWorkshop_4": "/allied-cultures/buildings/China_Porcelain_Workshop.webp",
        "Building_China_Workshop_PorcelainWorkshop_5": "/allied-cultures/buildings/China_Porcelain_Workshop.webp",
        "Building_China_Workshop_PorcelainWorkshop_6": "/allied-cultures/buildings/China_Porcelain_Workshop.webp",
    }
}

const vikingBuildings = {
    "Worker Home": {
        "Building_Vikings_Home_Worker_1": "/allied-cultures/buildings/Viking_Worker_Home_Lv1.webp",
        "Building_Vikings_Home_Worker_2": "/allied-cultures/buildings/Viking_Worker_Home_Lv2.webp",
        "Building_Vikings_Home_Worker_3": "/allied-cultures/buildings/Viking_Worker_Home_Lv3.webp",
        "Building_Vikings_Home_Worker_4": "/allied-cultures/buildings/Viking_Worker_Home_Lv4.webp",
        "Building_Vikings_Home_Worker_5": "/allied-cultures/buildings/Viking_Worker_Home_Lv5.webp",
        "Building_Vikings_Home_Worker_6": "/allied-cultures/buildings/Viking_Worker_Home_Lv6.webp",
    },
    "Sailor Home": {
        "Building_Vikings_Home_Sailor_1": "/allied-cultures/buildings/Viking_Sailor_Home_Lv1.webp",
        "Building_Vikings_Home_Sailor_2": "/allied-cultures/buildings/Viking_Sailor_Home_Lv2.webp",
        "Building_Vikings_Home_Sailor_3": "/allied-cultures/buildings/Viking_Sailor_Home_Lv3.webp",
        "Building_Vikings_Home_Sailor_4": "/allied-cultures/buildings/Viking_Sailor_Home_Lv4.webp",
        "Building_Vikings_Home_Sailor_5": "/allied-cultures/buildings/Viking_Sailor_Home_Lv5.webp",
        "Building_Vikings_Home_Sailor_6": "/allied-cultures/buildings/Viking_Sailor_Home_Lv6.webp",
    },
    "Luxurious Home": {
        "Building_Vikings_Home_Premium_1": "/allied-cultures/buildings/Viking_Luxurious_Home_Lv1.webp",
        "Building_Vikings_Home_Premium_2": "/allied-cultures/buildings/Viking_Luxurious_Home_Lv1.webp",
        "Building_Vikings_Home_Premium_3": "/allied-cultures/buildings/Viking_Luxurious_Home_Lv1.webp",
        "Building_Vikings_Home_Premium_4": "/allied-cultures/buildings/Viking_Luxurious_Home_Lv4.webp",
        "Building_Vikings_Home_Premium_5": "/allied-cultures/buildings/Viking_Luxurious_Home_Lv4.webp",
        "Building_Vikings_Home_Premium_6": "/allied-cultures/buildings/Viking_Luxurious_Home_Lv4.webp",
    },
    "Beehive": {
        "Building_Vikings_Beehive_Average_1": "/allied-cultures/buildings/Viking_Beehive_Lv1.webp",
        "Building_Vikings_Beehive_Average_2": "/allied-cultures/buildings/Viking_Beehive_Lv2.webp",
        "Building_Vikings_Beehive_Average_3": "/allied-cultures/buildings/Viking_Beehive_Lv3.webp",
        "Building_Vikings_Beehive_Average_4": "/allied-cultures/buildings/Viking_Beehive_Lv4.webp",
        "Building_Vikings_Beehive_Average_5": "/allied-cultures/buildings/Viking_Beehive_Lv5.webp",
        "Building_Vikings_Beehive_Average_6": "/allied-cultures/buildings/Viking_Beehive_Lv6.webp",
    },
    "Fishing Pier": {
        "Building_Vikings_FishingPier_Average_1": "/allied-cultures/buildings/Viking_Fishing_Pier_Lv1.webp",
        "Building_Vikings_FishingPier_Average_2": "/allied-cultures/buildings/Viking_Fishing_Pier_Lv2.webp",
        "Building_Vikings_FishingPier_Average_3": "/allied-cultures/buildings/Viking_Fishing_Pier_Lv3.webp",
        "Building_Vikings_FishingPier_Average_4": "/allied-cultures/buildings/Viking_Fishing_Pier_Lv4.webp",
        "Building_Vikings_FishingPier_Average_5": "/allied-cultures/buildings/Viking_Fishing_Pier_Lv5.webp",
        "Building_Vikings_FishingPier_Average_6": "/allied-cultures/buildings/Viking_Fishing_Pier_Lv6.webp",
    },
    "Luxurious Fishing Pier": {
        "Building_Vikings_FishingPier_Premium_1": "/allied-cultures/buildings/Viking_Luxurious_Fishing_Pier_Lv1.webp",
        "Building_Vikings_FishingPier_Premium_2": "/allied-cultures/buildings/Viking_Luxurious_Fishing_Pier_Lv1.webp",
        "Building_Vikings_FishingPier_Premium_3": "/allied-cultures/buildings/Viking_Luxurious_Fishing_Pier_Lv1.webp",
        "Building_Vikings_FishingPier_Premium_4": "/allied-cultures/buildings/Viking_Luxurious_Fishing_Pier_Lv4.webp",
        "Building_Vikings_FishingPier_Premium_5": "/allied-cultures/buildings/Viking_Luxurious_Fishing_Pier_Lv4.webp",
        "Building_Vikings_FishingPier_Premium_6": "/allied-cultures/buildings/Viking_Luxurious_Fishing_Pier_Lv4.webp",
    },
    "Tavern": {
        "Building_Vikings_Workshop_Tavern_1": "/allied-cultures/buildings/Viking_Tavern_Lv1.webp",
        "Building_Vikings_Workshop_Tavern_2": "/allied-cultures/buildings/Viking_Tavern_Lv1.webp",
        "Building_Vikings_Workshop_Tavern_3": "/allied-cultures/buildings/Viking_Tavern_Lv1.webp",
        "Building_Vikings_Workshop_Tavern_4": "/allied-cultures/buildings/Viking_Tavern_Lv4.webp",
        "Building_Vikings_Workshop_Tavern_5": "/allied-cultures/buildings/Viking_Tavern_Lv4.webp",
        "Building_Vikings_Workshop_Tavern_6": "/allied-cultures/buildings/Viking_Tavern_Lv4.webp",
    },
    "Expedition Pier": {
        "Building_Vikings_ExpeditionPier_Average_1": "/allied-cultures/buildings/Viking_Expedition_Pier.webp",
        "Building_Vikings_ExpeditionPier_Average_2": "/allied-cultures/buildings/Viking_Expedition_Pier.webp",
        "Building_Vikings_ExpeditionPier_Average_3": "/allied-cultures/buildings/Viking_Expedition_Pier.webp",
        "Building_Vikings_ExpeditionPier_Average_4": "/allied-cultures/buildings/Viking_Expedition_Pier.webp",
        "Building_Vikings_ExpeditionPier_Average_5": "/allied-cultures/buildings/Viking_Expedition_Pier.webp",
        "Building_Vikings_ExpeditionPier_Average_6": "/allied-cultures/buildings/Viking_Expedition_Pier.webp",
    },
    "Sailor Port": {
        "Building_Vikings_SailorPort_Average_1": "/allied-cultures/buildings/Viking_Sailor_Port.webp",
        "Building_Vikings_SailorPort_Average_2": "/allied-cultures/buildings/Viking_Sailor_Port.webp",
        "Building_Vikings_SailorPort_Average_3": "/allied-cultures/buildings/Viking_Sailor_Port.webp",
        "Building_Vikings_SailorPort_Average_4": "/allied-cultures/buildings/Viking_Sailor_Port.webp",
        "Building_Vikings_SailorPort_Average_5": "/allied-cultures/buildings/Viking_Sailor_Port.webp",
        "Building_Vikings_SailorPort_Average_6": "/allied-cultures/buildings/Viking_Sailor_Port.webp",
    },
    "Luxurious Sailor Port": {
        "Building_Vikings_SailorPort_Premium_1": "/allied-cultures/buildings/Viking_Luxurious_Sailor_Port_Lv1.webp",
        "Building_Vikings_SailorPort_Premium_2": "/allied-cultures/buildings/Viking_Luxurious_Sailor_Port_Lv1.webp",
        "Building_Vikings_SailorPort_Premium_3": "/allied-cultures/buildings/Viking_Luxurious_Sailor_Port_Lv1.webp",
        "Building_Vikings_SailorPort_Premium_4": "/allied-cultures/buildings/Viking_Luxurious_Sailor_Port_Lv1.webp",
        "Building_Vikings_SailorPort_Premium_5": "/allied-cultures/buildings/Viking_Luxurious_Sailor_Port_Lv1.webp",
        "Building_Vikings_SailorPort_Premium_6": "/allied-cultures/buildings/Viking_Luxurious_Sailor_Port_Lv1.webp",
    },
}

export { egyptBuildings, chinaBuildings, vikingBuildings };