const links = [
    {
        id: 1,
        url: "/",
        text: "Home",
        img: "/navbar/Navbar_Home.webp",
        show: true,
    },
    {
        id: 2,
        url: "/campaign",
        text: "Campaign",
        img: "/navbar/Navbar_Campaign.webp",
        show: true,
    },
    {
        id: 3,
        url: "/heroes",
        text: "Heroes",
        img: "/navbar/Navbar_Heroes.webp",
        show: true,
    },
    {
        id: 4,
        url: "/buildings",
        text: "Buildings",
        img: "/navbar/Navbar_Buildings.webp",
        show: true,
    },
    {
        id: 5,
        url: "/events",
        text: "Events",
        img: "/navbar/Navbar_Events.webp",
        show: true,
    },
    {
        id: 6,
        url: "/allied-cultures",
        text: "Allied Cultures",
        img: "/navbar/Navbar_AlliedCultures.webp",
        show: true,
    },
    {
        id: 7,
        url: "/research",
        text: "Research",
        img: "/navbar/Navbar_Research.webp",
        show: true,
    },
    {
        id: 8,
        url: "/treasure-hunt",
        text: "Treasure Hunt",
        img: "/navbar/Navbar_TreasureHunt.webp",
        show: true,
    },
    {
        id: 9,
        url: "/seasons",
        text: "Seasons",
        img: "/navbar/Navbar_Seasons.webp",
        show: true,
    },
    {
        id: 10,
        url: "/leaderboards",
        text: "Leaderboards",
        img: "/navbar/Navbar_Leaderboards.webp",
        show: true,
    },
    {
        id: 11,
        url: "/resources",
        text: "Resources",
        img: "/navbar/Navbar_Resources.webp",
        show: true,
    },
    {
        id: 12,
        url: "/tesla-storms",
        text: "Tesla Storms",
        img: "https://i.ibb.co/nRvy33n/event-widget-backer-time-Paradox-2021.png",
        show: false,
    },
    {
        id: 13,
        url: "/community",
        text: "Community",
        img: "/navbar/Navbar_Community.webp",
        show: true,
    },
]

export default links;