const allHeroes = [
    {
        id: "amelia-earhart",
        name: "Amelia Earhart",
        codeName: "AmeliaEarhart",
        image: "/heroes/intro/fullbody/Unit_AmeliaEarhart_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_AmeliaEarhart.webp",
        backdrop: "italy",
        stars: 5,
        heroClass: "great-leader",
        unit: "infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_ameliaearhart.webp",
        abilityName: "Tactical Evacuation",
        position: "backline",
        damageType: [],
        tacticalType: ["teleport", "heal", "buff"],
    },
    {
        id: "ragnar-lodbrok",
        name: "Ragnar Lodbrok",
        codeName: "RagnarLodbrok",
        image: "/heroes/intro/fullbody/Unit_RagnarLodbrok_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_RagnarLodbrok.webp",
        backdrop: "snow",
        stars: 5,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_ragnarlodbrok.webp",
        abilityName: "Lion of the North",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["debuff", "teleport", "shield"],
    },
    {
        id: "lagertha",
        name: "Lagertha",
        codeName: "Lagertha",
        image: "/heroes/intro/fullbody/Unit_Lagertha_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Lagertha.webp",
        backdrop: "snow",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_lagertha.webp",
        abilityName: "Thunderstrike",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: ["buff", "teleport"],
    },
    {
        id: "dracula",
        name: "Dracula",
        codeName: "Dracula",
        image: "/heroes/intro/fullbody/Unit_Dracula_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Dracula.webp",
        backdrop: "eternal_rivals",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_dracula.webp",
        abilityName: "Vampiric Essence",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: ["heal"],
    },
    {
        id: "leif-erikson",
        name: "Leif Erikson",
        codeName: "LeifErikson",
        image: "/heroes/intro/fullbody/Unit_LeifErikson_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_LeifErikson.webp",
        backdrop: "snow",
        stars: 4,
        heroClass: "manipulator",
        unit: "ranged",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_leiferikson.webp",
        abilityName: "Viking Curse",
        position: "backline",
        damageType: ["single_target"],
        tacticalType: ["debuff"],
    },
    {
        id: "cleopatra",
        name: "Cleopatra",
        codeName: "Cleopatra",
        image: "/heroes/intro/fullbody/Unit_Cleopatra_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Cleopatra.webp",
        backdrop: "egypt",
        stars: 5,
        heroClass: "great-leader",
        unit: "ranged",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_cleopatra.webp",
        abilityName: "Pharaoh's Puppets",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["buff"],
    },
    {
        id: "albert-einstein",
        name: "Albert Einstein",
        codeName: "AlbertEinstein",
        image: "/heroes/intro/fullbody/Unit_AlbertEinstein_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_AlbertEinstein.webp",
        backdrop: "modern",
        stars: 5,
        heroClass: "genius",
        unit: "siege",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_alberteinstein.webp",
        abilityName: "Everything is relative",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "benjamin-franklin",
        name: "Benjamin Franklin",
        codeName: "BenjaminFranklin",
        image: "/heroes/intro/fullbody/Unit_BenjaminFranklin_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_BenjaminFranklin.webp",
        backdrop: "modern",
        stars: 5,
        heroClass: "manipulator",
        unit: "ranged",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_benjaminfranklin.webp",
        abilityName: "Kite Conductor",
        position: "backline",
        damageType: [],
        tacticalType: ["stun", "debuff"],
    },
    {
        id: "julius-caesar",
        name: "Julius Caesar",
        codeName: "JuliusCaesar",
        image: "/heroes/intro/fullbody/Unit_JuliusCaesar_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_JuliusCaesar.webp",
        backdrop: "italy",
        stars: 5,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_juliuscaesar.webp",
        abilityName: "Veni, Vidi, Vici",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "leonardo-da-vinci",
        name: "Leonardo Da Vinci",
        codeName: "LeonardoDaVinci",
        image: "/heroes/intro/fullbody/Unit_LeonardoDaVinci_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_LeonardoDaVinci.webp",
        backdrop: "renaissance",
        stars: 5,
        heroClass: "genius",
        unit: "siege",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_leonardodavinci.webp",
        abilityName: "Vitruvian Vortex",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["debuff", "teleport"],
    },
    {
        id: "marie-curie",
        name: "Marie Curie",
        codeName: "MarieCurie",
        image: "/heroes/intro/fullbody/Unit_MarieCurie_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_MarieCurie.webp",
        backdrop: "windmill",
        stars: 5,
        heroClass: "genius",
        unit: "siege",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_mariecurie.webp",
        abilityName: "Radium Cascade",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "napoleon-bonaparte",
        name: "Napoleon Bonaparte",
        codeName: "NapoleonBonaparte",
        image: "/heroes/intro/fullbody/Unit_NapoleonBonaparte_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_NapoleonBonaparte.webp",
        backdrop: "baroque",
        stars: 5,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_napoleonbonaparte.webp",
        abilityName: "Code of Battle",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "queen-elisabeth-i",
        name: "Queen Elisabeth I",
        codeName: "QueenElizabethI",
        image: "/heroes/intro/fullbody/Unit_QueenElizabethI_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_QueenElizabethI.webp",
        backdrop: "windmill",
        stars: 5,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_queenelizabethi.webp",
        abilityName: "Tudor's Triumph",
        position: "backline",
        damageType: [],
        tacticalType: ["buff"],
    },
    {
        id: "sir-lancelot",
        name: "Sir Lancelot",
        codeName: "SirLancelot",
        image: "/heroes/intro/fullbody/Unit_SirLancelot_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_SirLancelot.webp",
        backdrop: "sunflower",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_sirlancelot.webp",
        abilityName: "Camelot's Avenger",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: [],
    },
    {
        id: "george-washington",
        name: "George Washington",
        codeName: "GeorgeWashington",
        image: "/heroes/intro/fullbody/Unit_GeorgeWashington_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_GeorgeWashington.webp",
        backdrop: "modern",
        stars: 5,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_georgewashington.webp",
        abilityName: "Father of Defenders",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["buff", "debuff"],
    },
    {
        id: "hercules",
        name: "Hercules",
        codeName: "Hercules",
        image: "/heroes/intro/fullbody/Unit_Hercules_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Hercules.webp",
        backdrop: "greek",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_hercules.webp",
        abilityName: "Titan's Strength",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "william-wallace",
        name: "William Wallace",
        codeName: "WilliamWallace",
        image: "/heroes/intro/fullbody/Unit_WilliamWallace_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_WilliamWallace.webp",
        backdrop: "grass",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_williamwallace.webp",
        abilityName: "Brave Heart",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["shield", "buff"],
    },
    {
        id: "robin-hood",
        name: "Robin Hood",
        codeName: "RobinHood",
        image: "/heroes/intro/fullbody/Unit_RobinHood_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_RobinHood.webp",
        backdrop: "grass",
        stars: 5,
        heroClass: "champion",
        unit: "ranged",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_robinhood.webp",
        abilityName: "Sherwood's Vengeance",
        position: "backline",
        damageType: ["single_target"],
        tacticalType: ["debuff"],
    },
    {
        id: "joan-of-arc",
        name: "Joan of Arc",
        codeName: "JoanOfArc",
        image: "/heroes/intro/fullbody/Unit_JoanOfArc_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_JoanOfArc.webp",
        backdrop: "windmill",
        stars: 5,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_joanofarc.webp",
        abilityName: "Beacon of Hope",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["heal"],
    },
    {
        id: "achilles",
        name: "Achilles",
        codeName: "Achilles",
        image: "/heroes/intro/fullbody/Unit_Achilles_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Achilles.webp",
        backdrop: "greek",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_achilles.webp",
        abilityName: "Achilles' Last Stand",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: ["buff"],
    },
    {
        id: "abraham-lincoln",
        name: "Abraham Lincoln",
        codeName: "AbrahamLincoln",
        image: "/heroes/intro/fullbody/Unit_AbrahamLincoln_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_AbrahamLincoln.webp",
        backdrop: "modern",
        stars: 5,
        heroClass: "great-leader",
        unit: "ranged",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_abrahamlincoln.webp",
        abilityName: "President's Protection",
        position: "backline",
        damageType: [],
        tacticalType: ["buff"],
    },
    {
        id: "medusa",
        name: "Medusa",
        codeName: "Medusa",
        image: "/heroes/intro/fullbody/Unit_Medusa_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Medusa.webp",
        backdrop: "greek",
        stars: 5,
        heroClass: "manipulator",
        unit: "ranged",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_medusa.webp",
        abilityName: "Petrifying Gaze",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["debuff", "stun"],
    },
    {
        id: "hua-mulan",
        name: "Hua Mulan",
        codeName: "HuaMulan",
        image: "/heroes/intro/fullbody/Unit_HuaMulan_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_HuaMulan.webp",
        backdrop: "china",
        stars: 5,
        heroClass: "champion",
        unit: "infantry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_huamulan.webp",
        abilityName: "Revenge of the Dragon",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "ramses-ii",
        name: "Ramses II",
        codeName: "RamsesII",
        image: "/heroes/intro/fullbody/Unit_RamsesII_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_RamsesII.webp",
        backdrop: "egypt",
        stars: 5,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_ramsesii.webp",
        abilityName: "Unity of Egypt",
        position: "backline",
        damageType: [],
        tacticalType: ["buff"],
    },
    {
        id: "sun-tzu",
        name: "Sun Tzu",
        codeName: "SunTzu",
        image: "/heroes/intro/fullbody/Unit_SunTzu_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_SunTzu.webp",
        backdrop: "china",
        stars: 5,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_suntzu.webp",
        abilityName: "Art of Defense",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "bessie-coleman",
        name: "Bessie Coleman",
        codeName: "BessieColeman",
        image: "/heroes/intro/fullbody/Unit_BessieColeman_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_BessieColeman.webp",
        backdrop: "italy",
        stars: 4,
        heroClass: "manipulator",
        unit: "ranged",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_bessiecoleman.webp",
        abilityName: "Smoke Flares",
        position: "backline",
        damageType: ["single_target"],
        tacticalType: ["debuff"],
    },
    {
        id: "abraham-van-helsing",
        name: "Abraham Van Helsing",
        codeName: "VanHelsing",
        image: "/heroes/intro/fullbody/Unit_VanHelsing_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_VanHelsing.webp",
        backdrop: "eternal_rivals",
        stars: 4,
        heroClass: "genius",
        unit: "ranged",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_vanhelsing.webp",
        abilityName: "Silver Bolts",
        position: "backline",
        damageType: ["single_target"],
        tacticalType: ["debuff"],
    },
    {
        id: "menes",
        name: "Menes",
        codeName: "Menes",
        image: "/heroes/intro/fullbody/Unit_Menes_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Menes.webp",
        backdrop: "egypt",
        stars: 4,
        heroClass: "genius",
        unit: "siege",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_menes.webp",
        abilityName: "Sandstorm Surge",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "spartacus",
        name: "Spartacus",
        codeName: "Spartacus",
        image: "/heroes/intro/fullbody/Unit_Spartacus_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Spartacus.webp",
        backdrop: "italy",
        stars: 4,
        heroClass: "champion",
        unit: "infantry",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_spartacus.webp",
        abilityName: "Brutal Gladiator",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: ["buff"],
    },
    {
        id: "tiger-lily",
        name: "Tiger Lily",
        codeName: "TigerLily",
        image: "/heroes/intro/fullbody/Unit_Pocahontas_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_TigerLily.webp",
        backdrop: "grass",
        stars: 4,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_tigerlily.webp",
        abilityName: "Tiger Lily's Pacification",
        position: "backline",
        damageType: [],
        tacticalType: ["heal"],
    },
    {
        id: "confucius",
        name: "Confucius",
        codeName: "Confucius",
        image: "/heroes/intro/fullbody/Unit_Confucius_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Confucius.webp",
        backdrop: "china",
        stars: 4,
        heroClass: "manipulator",
        unit: "ranged",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_confucius.webp",
        abilityName: "Confucian Confusion",
        position: "backline",
        damageType: [],
        tacticalType: ["buff", "debuff"],
    },
    {
        id: "hatshepsut",
        name: "Hatshepsut",
        codeName: "Hatshepsut",
        image: "/heroes/intro/fullbody/Unit_Hatshepsut_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Hatshepsut.webp",
        backdrop: "egypt",
        stars: 4,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_hatshepsut.webp",
        abilityName: "Thebes' Tranquility",
        position: "backline",
        damageType: [],
        tacticalType: ["heal"], //gives focus
    },
    {
        id: "jane-austen",
        name: "Jane Austen",
        codeName: "JaneAusten",
        image: "/heroes/intro/fullbody/Unit_JaneAusten_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_JaneAusten.webp",
        backdrop: "modern",
        stars: 4,
        heroClass: "manipulator",
        unit: "ranged",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_janeausten.webp",
        abilityName: "Pride and Prejudice",
        position: "backline",
        damageType: [],
        tacticalType: ["debuff", "buff", "stun"],
    },
    {
        id: "louis-xiv",
        name: "Louis XIV",
        codeName: "LouisXIV",
        image: "/heroes/intro/fullbody/Unit_LouisXIV_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_LouisXIV.webp",
        backdrop: "sunflower",
        stars: 4,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_louisxiv.webp",
        abilityName: "Roi-Soleil's Favour",
        position: "backline",
        damageType: [],
        tacticalType: ["buff", "shield"],
    },
    {
        id: "ludwig-van-beethoven",
        name: "Ludwig Van Beethoven",
        codeName: "LudwigVanBeethoven",
        image: "/heroes/intro/fullbody/Unit_LudwigvanBeethoven_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_LudwigVanBeethoven.webp",
        backdrop: "renaissance",
        stars: 4,
        heroClass: "genius",
        unit: "siege",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_ludwigvanbeethoven.webp",
        abilityName: "Ode to Destruction",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["stun"],
    },
    {
        id: "margaret-i-of-denmark",
        name: "Margaret I of Denmark",
        codeName: "MargaretIOfDenmark",
        image: "/heroes/intro/fullbody/Unit_MargaretIOfDenmark_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_MargaretIOfDenmark.webp",
        backdrop: "snow",
        stars: 4,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_margaretiofdenmark.webp",
        abilityName: "Nordic Nova",
        position: "backline",
        damageType: [],
        tacticalType: ["buff"],
    },
    {
        id: "plato",
        name: "Plato",
        codeName: "Plato",
        image: "",
        icon: "/heroes/intro/icons/Unit_Plato.webp",
        backdrop: "greek",
        stars: 4,
        heroClass: "manipulator",
        unit: "ranged",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_plato.webp",
        abilityName: "Dialogue's Disarray",
        position: "backline",
        damageType: [],
        tacticalType: ["debuff"],
    },
    {
        id: "vincent-van-gogh",
        name: "Vincent Van Gogh",
        codeName: "VincentVanGogh",
        image: "/heroes/intro/fullbody/Unit_VincentVanGogh_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_VincentVanGogh.webp",
        backdrop: "sunflower",
        stars: 4,
        heroClass: "genius",
        unit: "siege",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_vincentvangogh.webp",
        abilityName: "Starry Night Storm",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "tomoe-gozen",
        name: "Tomoe Gozen",
        codeName: "TomoeGozen",
        image: "/heroes/intro/fullbody/Unit_TomoeGozen_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_TomoeGozen.webp",
        backdrop: "china",
        stars: 4,
        heroClass: "champion",
        unit: "infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_tomoegozen.webp",
        abilityName: "Sakura Slash",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: [],
    },
    {
        id: "thomas-alva-edison",
        name: "Thomas Alva Edison",
        codeName: "ThomasAlvaEdison",
        image: "/heroes/intro/fullbody/Unit_Edison_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_ThomasAlvaEdison.webp",
        backdrop: "modern",
        stars: 4,
        heroClass: "genius",
        unit: "siege",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_thomasalvaedison.webp",
        abilityName: "Warp Shock",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["buff", "teleport"],
    },
    {
        id: "attila-the-hun",
        name: "Attila The Hun",
        codeName: "AttilaTheHun",
        image: "/heroes/intro/fullbody/Unit_AttilaTheHun_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_AttilaTheHun.webp",
        backdrop: "grass",
        stars: 4,
        heroClass: "commander",
        unit: "cavalry",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_attilathehun.webp",
        abilityName: "Horde Leader's Arrow",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: ["heal"],
    },
    {
        id: "charlemagne",
        name: "Charlemagne",
        codeName: "Charlemagne",
        image: "/heroes/intro/fullbody/Unit_Charlemagne_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Charlemagne.webp",
        backdrop: "sunflower",
        stars: 4,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_charlemagne.webp",
        abilityName: "Carolingian Valor",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "dartagnan",
        name: "D'artagnan",
        codeName: "DArtagnan",
        image: "/heroes/intro/fullbody/Unit_DArtagnan_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_DArtagnan.webp",
        backdrop: "sunflower",
        stars: 4,
        heroClass: "champion",
        unit: "infantry",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_dartagnan.webp",
        abilityName: "Musketeer's Vendetta",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: [],
    },
    {
        id: "king-minos",
        name: "King Minos",
        codeName: "KingMinos",
        image: "/heroes/intro/fullbody/Unit_KingMinos_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_KingMinos.webp",
        backdrop: "greek",
        stars: 4,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_kingminos.webp",
        abilityName: "Minotaur Guardian",
        position: "frontline",
        damageType: [],
        tacticalType: ["shield", "stun"],
    },
    {
        id: "queen-boudicca",
        name: "Queen Boudicca",
        codeName: "QueenBoudicca",
        image: "/heroes/intro/fullbody/Unit_QueenBoudicca_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_QueenBoudicca.webp",
        backdrop: "grass",
        stars: 4,
        heroClass: "champion",
        unit: "ranged",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_queenboudicca.webp",
        abilityName: "Celtic Vengeance",
        position: "backline",
        damageType: ["single_target"],
        tacticalType: ["stun"],
    },
    {
        id: "qin-shi-huang",
        name: "Qin Shi Huang",
        codeName: "QinShiHuang",
        image: "/heroes/intro/fullbody/Unit_QinShiHuang_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_QinShiHuang.webp",
        backdrop: "china",
        stars: 4,
        heroClass: "genius",
        unit: "siege",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_quinshihuang.webp",
        abilityName: "Spirit Sword",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["heal"],
    },
    {
        id: "miyamoto-musashi",
        name: "Miyamoto Musashi",
        codeName: "MiyamotoMusashi",
        image: "/heroes/intro/fullbody/Unit_MiyamotoMusashi_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_MiyamotoMusashi.webp",
        backdrop: "china",
        stars: 3,
        heroClass: "champion",
        unit: "infantry",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_miyamotomusashi.webp",
        abilityName: "Dual Blade Mastery",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: [],
    },
    {
        id: "cyrus-the-great",
        name: "Cyrus the Great",
        codeName: "CyrusTheGreat",
        image: "/heroes/intro/fullbody/Unit_CyrusTheGreat_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_CyrusTheGreat.webp",
        backdrop: "desert",
        stars: 3,
        heroClass: "commander",
        unit: "cavalry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_cyrusthegreat.webp",
        abilityName: "Achamenid Edict",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: [],
    },
    {
        id: "john-locke",
        name: "John Locke",
        codeName: "JohnLocke",
        image: "",
        icon: "/heroes/intro/icons/Unit_JohnLocke.webp",
        backdrop: "renaissance",
        stars: 3,
        heroClass: "manipulator",
        unit: "ranged",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_johnlocke.webp",
        abilityName: "Empirical Echo",
        position: "backline",
        damageType: ["single_target"],
        tacticalType: ["debuff"],
    },
    {
        id: "karl-marx",
        name: "Karl Marx",
        codeName: "KarlMarx",
        image: "/heroes/intro/fullbody/Unit_KarlMarx_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_KarlMarx.webp",
        backdrop: "sunflower",
        stars: 3,
        heroClass: "manipulator",
        unit: "ranged",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_karlmarx.webp",
        abilityName: "Manifesto Misdirection",
        position: "backline",
        damageType: [],
        tacticalType: ["debuff"],
    },
    {
        id: "mansa-musa",
        name: "Mansa Musa",
        codeName: "MansaMusa",
        image: "/heroes/intro/fullbody/Unit_MansaMusa_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_MansaMusa.webp",
        backdrop: "desert",
        stars: 3,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_mansamusa.webp",
        abilityName: "Gold-Coast Gambit",
        position: "backline",
        damageType: [],
        tacticalType: ["buff"],
    },
    {
        id: "marco-polo",
        name: "Marco Polo",
        codeName: "MarcoPolo",
        image: "/heroes/intro/fullbody/Unit_MarcoPolo_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_MarcoPolo.webp",
        backdrop: "renaissance",
        stars: 3,
        heroClass: "genius",
        unit: "siege",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_marcopolo.webp",
        abilityName: "Burst of Discovery",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: ["teleport"],
    },
    {
        id: "oracle-of-dephi",
        name: "Oracle of Dephi",
        codeName: "OracleOfDephi",
        image: "/heroes/intro/fullbody/Unit_OracleofDephi_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_OracleOfDephi.webp",
        backdrop: "greek",
        stars: 3,
        heroClass: "manipulator",
        unit: "ranged",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_oracleofdephi.webp",
        abilityName: "Oracle's Omen",
        position: "backline",
        damageType: [],
        tacticalType: ["debuff"],
    },
    {
        id: "ada-lovelace",
        name: "Ada Lovelace",
        codeName: "AdaLovelace",
        image: "/heroes/intro/fullbody/Unit_AdaLovelace_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_AdaLovelace.webp",
        backdrop: "sunflower",
        stars: 3,
        heroClass: "genius",
        unit: "siege",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_adalovelace.webp",
        abilityName: "Logic Bomb",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: [],
    },
    {
        id: "artemisia-i-of-caria",
        name: "Artemisia I of Caria",
        codeName: "ArtemisiaIOfCaria",
        image: "/heroes/intro/fullbody/Unit_ArtemisiaIOfCaria_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_ArtemisiaIOfCaria.webp",
        backdrop: "desert",
        stars: 3,
        heroClass: "champion",
        unit: "ranged",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_artemisiaiofcaria.webp",
        abilityName: "Storm of Arrows",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: [],
    },
    {
        id: "pythagoras",
        name: "Pythagoras",
        codeName: "Pythagoras",
        image: "/heroes/intro/fullbody/Unit_Pythagoras_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Pythagoras.webp",
        backdrop: "greek",
        stars: 3,
        heroClass: "genius",
        unit: "siege",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_pythagoras.webp",
        abilityName: "Pythagorean Theorem",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: [],
    },
    {
        id: "hermann-the-cheruscan",
        name: "Hermann the Cheruscan",
        codeName: "HermannTheCheruscan",
        image: "/heroes/intro/fullbody/Unit_HermannTheCheruscan_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_HermannTheCheruscan.webp",
        backdrop: "grass",
        stars: 3,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_hermannthecheruscan.webp",
        abilityName: "Teutonic Tremor",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["heal"],
    },
    {
        id: "inanna",
        name: "Inanna",
        codeName: "Inanna",
        image: "/heroes/intro/fullbody/Unit_Inanna_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Inanna.webp",
        backdrop: "desert",
        stars: 3,
        heroClass: "champion",
        unit: "infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_inanna.webp",
        abilityName: "Swift Strike",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: [],
    },
    {
        id: "otto-von-bismarck",
        name: "Otto Von Bismarck",
        codeName: "OttoVonBismarck",
        image: "/heroes/intro/fullbody/Unit_OttoVonBismarck_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_OttoVonBismarck.webp",
        backdrop: "baroque",
        stars: 3,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_ottovonbismarck.webp",
        abilityName: "Iron Chancellor",
        position: "frontline",
        damageType: [],
        tacticalType: ["shield", "stun"],
    },
    {
        id: "ulysses-s-grant",
        name: "Ulysses S. Grant",
        codeName: "UlyssesSGrant",
        image: "/heroes/intro/fullbody/Unit_UlyssesSGrant_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_UlyssesSGrant.webp",
        backdrop: "modern",
        stars: 3,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_ulyssessgrant.webp",
        abilityName: "Union Rejuvenation",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: ["heal"],
    },
    {
        id: "ashoka-the-great",
        name: "Ashoka the Great",
        codeName: "AshokaTheGreat",
        image: "/heroes/intro/fullbody/Unit_AshokaTheGreat_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_AshokaTheGreat.webp",
        backdrop: "rainforest",
        stars: 3,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_ashokathegreat.webp",
        abilityName: "Dharma's Divinity",
        position: "backline",
        damageType: [],
        tacticalType: ["heal"],
    },
    {
        id: "leonidas-i",
        name: "Leonidas I.",
        codeName: "Leonidas",
        image: "/heroes/intro/fullbody/Unit_Leonidas_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Leonidas.webp",
        backdrop: "greek",
        stars: 3,
        heroClass: "champion",
        unit: "infantry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_leonidas.webp",
        abilityName: "This is Sparta!",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["stun"],
    },
    {
        id: "william-tell",
        name: "William Tell",
        codeName: "WilliamTell",
        image: "/heroes/intro/fullbody/Unit_WilliamTell_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_WilliamTell.webp",
        backdrop: "windmill",
        stars: 3,
        heroClass: "champion",
        unit: "ranged",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_williamtell.webp",
        abilityName: "Apple Splitter",
        position: "backline",
        damageType: ["single_target"],
        tacticalType: [],
    },
    {
        id: "maori-chief",
        name: "Te Wherowhero",
        codeName: "MaoriChief",
        image: "/heroes/intro/fullbody/Unit_MaoriChief_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_MaoriChief.webp",
        backdrop: "rainforest",
        stars: 2,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_maorichief.webp",
        abilityName: "Haka Huddle",
        position: "backline",
        damageType: [],
        tacticalType: ["shield"],
    },
    {
        id: "geisha",
        name: "Yoshino Dayu",
        codeName: "Geisha",
        image: "/heroes/intro/fullbody/Unit_Geisha_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Geisha.webp",
        backdrop: "china",
        stars: 2,
        heroClass: "manipulator",
        unit: "ranged",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_geisha.webp",
        abilityName: "Sakura Strike",
        position: "backline",
        damageType: ["single_target"],
        tacticalType: ["debuff"],
    },
    {
        id: "greek-mathematician",
        name: "Euclid",
        codeName: "GreekMathematician",
        image: "/heroes/intro/fullbody/Unit_GreekMathematician_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_GreekMathematician.webp",
        backdrop: "greek",
        stars: 2,
        heroClass: "genius",
        unit: "siege",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_greekmathematician.webp",
        abilityName: "Axiomatic Assault",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: [],
    },
    {
        id: "mayan-astronomer",
        name: "Itzamnaaj Bahlam III",
        codeName: "MayanAstronomer",
        image: "/heroes/intro/fullbody/Unit_MayanAstronomer_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_MayanAstronomer.webp",
        backdrop: "rainforest",
        stars: 2,
        heroClass: "genius",
        unit: "siege",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_mayanastronomer.webp",
        abilityName: "Cosmic Blast",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: [],
    },
    {
        id: "roman-praetor",
        name: "Aemilia Tertia",
        codeName: "RomanPraetor",
        image: "/heroes/intro/fullbody/Unit_RomanPraetor_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_RomanPraetor.webp",
        backdrop: "italy",
        stars: 2,
        heroClass: "manipulator",
        unit: "ranged",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_romanpraetor.webp",
        abilityName: "Legion's Lull",
        position: "backline",
        damageType: [],
        tacticalType: ["debuff"],
    },
    {
        id: "sioux-shaman",
        name: "Sitting Bull",
        codeName: "SiouxShaman",
        image: "/heroes/intro/fullbody/Unit_SiouxShaman_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_SiouxShaman.webp",
        backdrop: "grass",
        stars: 2,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_siouxshaman.webp",
        abilityName: "Spirit of Tatanka",
        position: "backline",
        damageType: [],
        tacticalType: ["buff"],
    },
    {
        id: "tribal-healer",
        name: "Naya of the Cave Clan",
        codeName: "TribalHealer",
        image: "/heroes/intro/fullbody/Unit_TribalHealer_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_TribalHealer.webp",
        backdrop: "grass",
        stars: 2,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_tribalhealer.webp",
        abilityName: "Healing Salve",
        position: "backline",
        damageType: [],
        tacticalType: ["heal"],
    },
    {
        id: "roman-centurion",
        name: "Titus Pullo",
        codeName: "RomanCenturion",
        image: "/heroes/intro/fullbody/Unit_RomanCenturion_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_RomanCenturion.webp",
        backdrop: "italy",
        stars: 2,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_romancenturion.webp",
        abilityName: "Turtle Formation",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: ["shield"],
    },
    {
        id: "egyptian-vizier",
        name: "Imhotep",
        codeName: "EgyptianVizier",
        image: "/heroes/intro/fullbody/Unit_EgyptianVizier_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_EgyptianVizier.webp",
        backdrop: "egypt",
        stars: 2,
        heroClass: "manipulator",
        unit: "ranged",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_egyptianvizier.webp",
        abilityName: "Vizier's Veil",
        position: "backline",
        damageType: [],
        tacticalType: ["debuff"],
    },
    {
        id: "ninja",
        name: "Mochizuki Chiyome",
        codeName: "Ninja",
        image: "/heroes/intro/fullbody/Unit_Ninja_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Ninja.webp",
        backdrop: "china",
        stars: 2,
        heroClass: "champion",
        unit: "ranged",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_ninja.webp",
        abilityName: "Whispering Blade",
        position: "backline",
        damageType: ["single_target"],
        tacticalType: [],
    },
    {
        id: "viking-jarl",
        name: "Erik the Red",
        codeName: "VikingJarl",
        image: "/heroes/intro/fullbody/Unit_VikingJarl_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_VikingJarl.webp",
        backdrop: "snow",
        stars: 2,
        heroClass: "great-leader",
        unit: "cavalry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_vikingjarl.webp",
        abilityName: "Berserker's Boost",
        position: "backline",
        damageType: [],
        tacticalType: ["buff"],
    },
    {
        id: "aztec-tlacateccatl",
        name: "Cuauhtemoc",
        codeName: "AztecTlacateccatl",
        image: "/heroes/intro/fullbody/Unit_AztecTlacateccatl_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_AztecTlacateccatl.webp",
        backdrop: "rainforest",
        stars: 2,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_aztectlacateccatl.webp",
        abilityName: "Sun God's Embrace",
        position: "frontline",
        damageType: [],
        tacticalType: ["heal"],
    },
    {
        id: "hoplit",
        name: "Miltiades",
        codeName: "Hoplit",
        image: "/heroes/intro/fullbody/Unit_Hoplit_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Hoplit.webp",
        backdrop: "greek",
        stars: 2,
        heroClass: "champion",
        unit: "infantry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_hoplit.webp",
        abilityName: "Piercing Thrust",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: [],
    },
    {
        id: "jaguar-warrior",
        name: "Ocelotl",
        codeName: "JaguarWarrior",
        image: "/heroes/intro/fullbody/Unit_JaguarWarrior_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_JaguarWarrior.webp",
        backdrop: "rainforest",
        stars: 2,
        heroClass: "champion",
        unit: "infantry",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_jaguarwarrior.webp",
        abilityName: "Jungle Predator",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: [],
    },
    {
        id: "japanese-shogun",
        name: "Kondo Isami",
        codeName: "JapaneseShogun",
        image: "/heroes/intro/fullbody/Unit_JapaneseShogun_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_JapaneseShogun.webp",
        backdrop: "china",
        stars: 2,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "blue",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_japaneseshogun.webp",
        abilityName: "Ikedaya Duskblade",
        position: "frontline",
        damageType: ["area_damage"],
        tacticalType: ["debuff"],
    },
    {
        id: "ottoman-general",
        name: "Hasan Pasha",
        codeName: "OttomanGeneral",
        image: "/heroes/intro/fullbody/Unit_OttomanGeneral_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_OttomanGeneral.webp",
        backdrop: "desert",
        stars: 2,
        heroClass: "commander",
        unit: "heavy-infantry",
        color: "green",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_ottomangeneral.webp",
        abilityName: "Ottoman Rampart",
        position: "frontline",
        damageType: [],
        tacticalType: ["stun", "buff"],
    },
    {
        id: "shaolin",
        name: "Xueting Fuyu",
        codeName: "Shaolin",
        image: "/heroes/intro/fullbody/Unit_Shaolin_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Shaolin.webp",
        backdrop: "china",
        stars: 2,
        heroClass: "champion",
        unit: "infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_shaolin.webp",
        abilityName: "Dragon Kick",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: [],
    },
    {
        id: "jester",
        name: "Triboulet",
        codeName: "Jester",
        image: "/heroes/intro/fullbody/Unit_Jester_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_Jester.webp",
        backdrop: "windmill",
        stars: 2,
        heroClass: "genius",
        unit: "siege",
        color: "purple",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_jester.webp",
        abilityName: "Confetti Cannon",
        position: "backline",
        damageType: ["area_damage"],
        tacticalType: [],
    },
    {
        id: "nubian-mercenary",
        name: "Kandake of Nubia",
        codeName: "NubianMercenary",
        image: "/heroes/intro/fullbody/Unit_NubianMercenary_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_NubianMercenary.webp",
        backdrop: "desert",
        stars: 2,
        heroClass: "champion",
        unit: "infantry",
        color: "yellow",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_nubianmercenary.webp",
        abilityName: "Desert Viper",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: [],
    },
    {
        id: "viking-raider",
        name: "Freydis Eiriksdottir",
        codeName: "VikingRaider",
        image: "/heroes/intro/fullbody/Unit_VikingRaider_fullbody.webp",
        icon: "/heroes/intro/icons/Unit_VikingRaider.webp",
        backdrop: "snow",
        stars: 2,
        heroClass: "champion",
        unit: "infantry",
        color: "red",
        abilityIcon: "/heroes/intro/abilities/icon_hero_battle_ability_vikingraider.webp",
        abilityName: "Axe of Ragnarok",
        position: "frontline",
        damageType: ["single_target"],
        tacticalType: [],
    },
]

const heroClassIcons = {
    "champion": "/heroes/intro/classIcons/icon-class-champion.webp",
    "commander": "/heroes/intro/classIcons/icon-class-commander.webp",
    "genius": "/heroes/intro/classIcons/icon-class-genius.webp",
    "great-leader": "/heroes/intro/classIcons/icon-class-great-leader.webp",
    "manipulator": "/heroes/intro/classIcons/icon-class-manipulator.webp",
}

const heroClassNames = {
    "champion": "Champion",
    "commander": "Commander",
    "genius": "Genius",
    "great-leader": "GreatLeader",
    "manipulator": "Manipulator",
}

const unitIcons = {
    "cavalry": "/heroes/intro/unitIcons/icon-flat-unit-cavalry.webp",
    "heavy-infantry": "/heroes/intro/unitIcons/icon-flat-unit-heavy-infantry.webp",
    "infantry": "/heroes/intro/unitIcons/icon-flat-unit-melee.webp",
    "ranged": "/heroes/intro/unitIcons/icon-flat-unit-range.webp",
    "siege": "/heroes/intro/unitIcons/icon-flat-unit-siege-units.webp",
}

const unitNames = {
    "cavalry": "Cavalry",
    "heavy-infantry": "Heavy Infantry",
    "infantry": "Infantry",
    "ranged": "Ranged",
    "siege": "Siege",
}

const colorIcons = {
    "red": "/heroes/intro/colorIcons/icon-colour-red.webp",
    "yellow": "/heroes/intro/colorIcons/icon-colour-yellow.webp",
    "green": "/heroes/intro/colorIcons/icon-colour-green.webp",
    "blue": "/heroes/intro/colorIcons/icon-colour-blue.webp",
    "purple": "/heroes/intro/colorIcons/icon-colour-purple.webp",
}

const colorNames = {
    "yellow": "Yellow",
    "red": "Red",
    "purple": "Purple",
    "blue": "Blue",
    "green": "Green",
}

const positionNames = {
    "frontline": "Frontline",
    "backline": "Backline",
}

const damageTypeNames = {
    "area_damage": "Area Damage",
    "single_target": "Single Target",
}

const tacticalTypeNames = {
    "buff": "Buff",
    "debuff": "Debuff",
    "heal": "Heal",
    "stun": "Stun",
    "shield": "Shield",
    "teleport": "Teleport",
}

const backdrops = {
    "baroque": "/heroes/intro/backdrops/hero-backdrop-baroque.webp",
    "china": "/heroes/intro/backdrops/hero-backdrop_china.webp",
    "desert": "/heroes/intro/backdrops/hero-backdrop-desert.webp",
    "egypt": "/heroes/intro/backdrops/hero-backdrop-egypt.webp",
    "grass": "/heroes/intro/backdrops/hero-backdrop-grass.webp",
    "greek": "/heroes/intro/backdrops/hero-backdrop-greek.webp",
    "italy": "/heroes/intro/backdrops/hero-backdrop-italy.webp",
    "modern": "/heroes/intro/backdrops/hero-backdrop-modern.webp",
    "rainforest": "/heroes/intro/backdrops/hero-backdrop-rainforest.webp",
    "renaissance": "/heroes/intro/backdrops/hero-backdrop-renaissance.webp",
    "snow": "/heroes/intro/backdrops/hero-backdrop-snow.webp",
    "sunflower": "/heroes/intro/backdrops/hero-backdrop-sunflower.webp",
    "windmill": "/heroes/intro/backdrops/hero-backdrop-windmill.webp",
    "eternal_rivals": "/heroes/intro/backdrops/hero-backdrop-eternal-rivals.webp",
}

export { allHeroes, heroClassIcons, heroClassNames, unitIcons, unitNames, colorIcons, colorNames, positionNames, damageTypeNames, tacticalTypeNames, backdrops };